# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97aa2af5c01930c071bb75aa49f7ee175124e9ee0a4580dfd8e4e5b33498af302fc641a1f113b4ae7f40c6d5706a622f8ba6de0fa89f7109f7b1e795a684c236

test:
  secret_key_base: b8b25786760a8097d3f62182923e3f7f526378015d87a01f9163398c8c3025a51a86ba2fe65c0f9c1974c290e2d73e13b13bad1118b9c4662160162add27482a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
